### PR TITLE
Add PyPy 3.9 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
Both currently supported versions of PyPy3 fail our tests.  :-(  https://www.pypy.org/download.html

@ddoroshev Do you have any ideas about how to fix?

### CODE REVIEW

**Comment by ddoroshev** [comment]
> Do you have any ideas about how to fix?

Well, I have zero ideas about what going on there. Actually, I know just a little bit about PyPy, and I know nothing about whoosh library and its tests. But, looking at the failing test, I can tell that a few hours of step-by-step debugging, comparing the behaviour between CPython and PyPy, will give you the answers.

**Comment by ZeroCool940711** [comment]
I'm looking into this, I think I have sort of found where one of the issues is tho. I think we have to look more closely at the tests we have. I fixed an issue with `test_automata.py` but I'm now getting errors in other tests which I am looking into.

**Comment by cclauss** [comment]
Add `DFA.__repr__()` to aid debugging...
```
    assert dfa == good
AssertionError: assert DFA:   2\n  3\n@ 5\n == DFA: @ 1\n  2\n  3\n
```

**Comment by ZeroCool940711** [comment]
> Even the latest version of PyPy (v7.3.14) makes no difference,
> 
> Add `DFA.__repr__()` to aid debugging...
> 
> ```
>     assert dfa == good
> AssertionError: assert DFA:   2\n  3\n@ 5\n == DFA: @ 1\n  2\n  3\n
> ```

Yeah, I tried debugging the `test_minimize_dfa` function and a few other parts of the code with no luck. Maybe using an older version of PyPy might help, it could be that something changed on the newer versions, remember that Whoosh hasn't been updated in more than 5 years, maybe we should look into what version was used back then and if it works now, then start updating from there.

**Comment by cclauss** [comment]
https://downloads.python.org/pypy/ pypy-3.8-v7.3.6 is the earliest version that supports Py38 and it still fails in the same way.

**Comment by ZeroCool940711** [comment]
@cclauss I found a library called [Pythomata](https://github.com/whitemech/pythomata) which I think we can use to replace most if not all the code from the `src/whoosh/automata` folder and some parts of the test files we use that are giving us trouble. We could either just add the dependency to the `setup.py` to use the library directly or we could just copy/paste the code and reuse it as part of Whoosh itself. I think it's better to just use the library itself since it will reduce the size of the source code and make it easier to maintain and if the Pythomata library is updated in the future we can benefit from the changes, if things break we can just use an older version of the library that works until things get fixed on our end.

**Comment by cclauss** [comment]
Solarlint does not support Python.  Use ruff instead.  https://docs.astral.sh/ruff

**Comment by ZeroCool940711** [comment]
> Solarlint does not support Python. Use ruff instead. [docs.astral.sh/ruff](https://docs.astral.sh/ruff)

I was testing it because it looks interesting. Anything that can help to improve our code is welcome. Their bot and website seem to do a pretty good job with Python tho, not sure about their VSCode extension tho. I will check ruff as well and see how they compare.

**Pull request closed without merging**
