### PR TITLE
Code formatting: ruff format . && ruff --select=I --fix .

### PR DESCRIPTION
**Pull request by cclauss**
# Description

`ruff format . && ruff --select=I --fix .`

Replaces both `black` and `isort` with `ruff` running rapidly in `pre-commit`.

This separates automatic formatting changes (this PR) from more manual and syntactical changes (in #54) to make the latter easier to review and revert if necessary.

# Checklist:

- [x] I have performed a self-review of my code
- [ ] I have added comments to code where it is hard to understand
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ZeroCool940711** [comment]
I will merge your PR and then work on fixing whatever breaks, since we have a stable version of the repo that can be installed on Pypi and the repo is supposed to be an unstable/development version.

**Comment by cclauss** [comment]
I am not a fan of merging pull requests that have failing tests.

**Comment by ZeroCool940711** [comment]
> I am not a fan of merging pull requests that have failing tests.

Me neither. I usually try to fix the tests before merging but this is a special case since it has a lot of changes that need to be fixed and most likely will some time to do so. Maybe we could work on a dev branch tho, merge there even if things break just so we can have a branch with everything in a single place instead of several different branches and we can keep the `main` branch clean.

**Comment by cclauss** [comment]
Each PR should be a "dev" branch and we should use `main` as the branch that ___always___ passes the tests.

**Comment by ZeroCool940711** [comment]
> Each PR should be a "dev" branch and we should use `main` as the branch that _**always**_ passes the tests.

Noted. Will keep that in mind from now on. I will try to fix this as fast as I can today to make the main branch pass the tests again.

**Comment by cclauss** [comment]
Do not rush.  Circular imports with import * can be thorny to fix.  This is one of the reasons that PEP8 strongly recommends avoiding * imports.

**Comment by ZeroCool940711** [comment]
@cclauss I think I fixed all the tests with PR #56. I just merged that into main.

**Pull request merged**
